org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official
android.nonTransitiveRClass=true
android.sdk.dir=../build-tools/android-sdk

# 本机 JDK 17 绑定（由环境配置生成，路径机器相关）
org.gradle.java.home=C:/Users/b5311/WorkBuddy/2026-09-15-10-37-12/yinfu-music/build-tools/jdk-17
