org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official
android.nonTransitiveRClass=true
android.sdk.dir=../build-tools/android-sdk

# 本机 JDK 17 绑定（由环境配置生成，路径机器相关）
org.gradle.java.home=C:/Users/jay/WorkBuddy/2026-09-09-11-22-17/build-tools/jdk/jdk-17.0.20.1+1
